name: Deploy to Streamlit Sharing

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install protobuf==3.20.1
        pip install --upgrade streamlit
        pip install -r requirements.txt

    - name: Deploy to Streamlit Sharing
      run: |
        bash streamlit_share_eportes123_paginawebapp.sh
      env:
        STREAMLIT_API_KEY: ${{ secrets.STREAMLIT_API_KEY }}
