name: Streamlit Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install plotly

      - name: Change to App Directory
        run: cd $GITHUB_WORKSPACE

      - name: Check Python Version and Path
        run: |
          which python
          python --version

      - name: Deploy Streamlit App
        run: |
          streamlit run streamlit_app.py &
          sleep 5  # Da tiempo a que Streamlit se inicie

      - name: Install Streamlit Sharing CLI
        run: pip install streamlit

      - name: Streamlit Sharing Deploy
        run: streamlit deploy --app eportes123/paginawebapp --secret api_key=$STREAMLIT_API_KEY
        env:
          STREAMLIT_API_KEY: ${{ secrets.STREAMLIT_API_KEY }}

